spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always