spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082
