FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# React 애플리케이션 빌드
RUN npm run build

# 정적 파일 제공을 위한 serve 설치
RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build"]