spring:
  application:
    name: graphql-service
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/graphqldb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true