AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating ALB and EC2 instances for weplat-ap2 VPC.

Parameters:
  AMI:
    Type: AWS::EC2::Image::Id
    Default: ami-040c33c6a51fd5d96 # Replace with the actual AMI ID for Ubuntu 24.04 LTS in your region
  KeyPairName:
    Description: Name of an existing EC2 Key Pair to enable SSH access
    Type: String
    Default: weplat2-ap2-key

Resources:
  WebServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SubnetId: !ImportValue WeplatSubnetPrivate1Id
      SecurityGroupIds:
        - !ImportValue WeplatAp2WebSGId
      ImageId: !Ref AMI
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            DeleteOnTermination: true # 종료 시 삭제
      DisableApiTermination: true # API를 통한 종료 방지
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |
                #!/bin/bash
              - sudo yum -y update
              - sudo amazon-linux-extras install docker
              - sudo service docker start
              - sudo usermod -a -G docker ec2-user
              - sudo yum install python3-pip
              - sudo pip3 install docker-compose
              - docker-compose --version
              - docker --version
      Tags:
        - Key: Name
          Value: weplat2-ap2-Web-1
  DevWebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: weplat2-ap2-dev-web-alb-tg
      Protocol: HTTP
      Port: 3001
      VpcId: !ImportValue WeplatVPCId
      HealthCheckPath: /
      HealthCheckEnabled: true
      HealthCheckPort: "traffic-port" # 기본값(정의된 프로토콜 및 포트 사용)
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 10 # 10초마다
      HealthCheckTimeoutSeconds: 5 # 5초 이내 응답 없으면 실패
      HealthyThresholdCount: 3 # 3번 성공시
      UnhealthyThresholdCount: 2 # 2번 실패시
      Targets:
        - Id: !Ref WebServer1
  ProdWebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: weplat2-ap2-prod-web-alb-tg
      Protocol: HTTP
      Port: 3002
      VpcId: !ImportValue WeplatVPCId
      HealthCheckPath: /
      HealthCheckEnabled: true
      HealthCheckPort: "traffic-port" # 기본값(정의된 프로토콜 및 포트 사용)
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 10 # 10초마다
      HealthCheckTimeoutSeconds: 5 # 5초 이내 응답 없으면 실패
      HealthyThresholdCount: 3 # 3번 성공시
      UnhealthyThresholdCount: 2 # 2번 실패시
      Targets:
        - Id: !Ref WebServer1

  WebLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: weplat2-ap2-web-alb
      Subnets:
        - !ImportValue WeplatSubnetPublic1Id
        - !ImportValue WeplatSubnetPublic2Id
      SecurityGroups:
        - !ImportValue WeplatAp2ExtAlbSGId
      Scheme: internet-facing
      LoadBalancerAttributes: # 로드 밸런서 속성
        - Key: deletion_protection.enabled # 삭제 방지 활성화
          Value: "true" # 활성화
  WebLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WebLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DevWebTargetGroup

  # ALB 리스너 규칙 추가
  DevListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref WebLoadBalancerListener
      Conditions:
        - Field: host-header
          Values:
            - dev.example.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref DevWebTargetGroup
      Priority: 10 # 가장 먼저 매칭되는 규칙
  ProdListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref WebLoadBalancerListener
      Conditions:
        - Field: host-header
          Values:
            - prod.example.com
            - www.example.com
            - example.com
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ProdWebTargetGroup
      Priority: 20 # 두 번째로 매칭되는 규칙