spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
---
spring.config.activate.on-profile: local

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
hello-spring:
  datasource:
    main:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db-main;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: main-db-pool
