version: '3.3'

services:
  server1:
    build:
      context: .
      dockerfile: go.Dockerfile
#    command: go run ./main -port 8080
#    volumes:
#      - .:/app
#    expose:
#      - "8080"
  nginx:
    image: nginx:1.15-alpine
    restart:
      unless-stopped
    volumes:
      - ./data/nginx/my-nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
      - server1
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"