apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mainui
spec:
    spec:
      containers:
        - name: apache-container
          image: httpd:2.2
          ports:
            - containerPort: 80s
              protocol: TCP

