server:
  port: 9000


#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          oidc-client:
#            registration:
#              client-id: "oauth2-client-app"
#              client-secret: "{noop}secret"
#              client-authentication-methods:
#                - client_secret_basic
#                - client_secret_post
#              authorization-grant-types:
#                - authorization_code
#                - refresh_token
#                - client_credentials
#              redirect-uris:
#                - "http://127.0.0.1:8081"
##              post-logout-redirect-uris:
##                - "http://localhost:8081"
##                - "http://localhost:8081/logout"
#              scopes:
#                - openid
#                - read
#                - write
#            require-authorization-consent: true
