// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"di-practice/wire_practice"
)

// Injectors from wire.go:

func InitializeBar() *wire_practice.Bar {
	foo := wire_practice.NewFoo()
	bar := wire_practice.NewBar(foo)
	return bar
}
