apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname" # app가 backend인 pod와 같은 노드에 배치
              labelSelector:
                matchLabels:
                  app: backend
      containers:
        - name: mainui
          image: nginx:1.14
          ports:
            - containerPort: 80