apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
spec:
  containers:
    - name: tensorflow-gpu
      image: tensorflow/tensorflow:nightly-jupyter
      ports:
        - containerPort: 8888
          protocol: TCP
  nodeSelector:
    gpu: "true"