server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {google-client-id}
            client-secret: {google-client-secret}
            scope: profile, email, openid

          # 네이버 OpenID Connect 지원 안함
          naver:
            client-id: {naver-client-id}
            client-secret: {naver-client-secret}
            authorization-grant-type: authorization_code
            client-name: naver-spring-oauth2
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile, email # openid는 안됨
            provider: naver

          # 카카오 OpenID Connect 사용중
          kakao:
            client-id: { kakao-client-id }
            client-secret: { kakao-client-secret }
            authorization-grant-type: authorization_code
            client-name: spring-oauth2
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            scope: profile_image, account_email, profile_nickname
            provider: kakao

        provider:

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 임시 코드 발급
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuer-uri: https://kauth.kakao.com

