apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    role: web
spec:
  containers:
    - name: web
      image: nginx:1.14
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
  restartPolicy: Always
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: pvc-web
