# 1. Stack 생성
# aws cloudformation create-stack \
#   --stack-name stack-weplat2-ap2-ecs-was-task-definition \
#   --template-body file://ecs/07_was_task_definition_cloudformation.yaml \
#   --capabilities CAPABILITY_NAMED_IAM
# 2. Stack 업데이트
# aws cloudformation update-stack \
# --stack-name stack-weplat2-ap2-ecs-was-task-definition \
# --template-body file://ecs/07_was_task_definition_cloudformation.yaml \
# --capabilities CAPABILITY_NAMED_IAM
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for ECS Task Definition

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/ecs/app-was"
      RetentionInDays: 7
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "app-was-td"
      Cpu: "512" # 0.5 vCPU
      Memory: "2048" # 2GB
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !ImportValue AppWebExecutionRoleArn
      TaskRoleArn: !ImportValue AppWasTaskRoleArn
      ContainerDefinitions:
        - Name: "app-was"
          Image: !ImportValue AppWasEcrRepositoryUri
          Essential: true
          PortMappings:
            - ContainerPort: 8081
              Protocol: tcp
              Name: "app-was-8081-tcp"
              AppProtocol: "http"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: "/ecs/app-was"
              awslogs-region: "ap-northeast-2"
              awslogs-stream-prefix: "app-was"

Outputs:
  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
    Description: ARN of the ECS Task Definition
    Export:
      Name: AppWasTaskDefinitionArn