spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: rental-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4=utf8mb4&8useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:my-secret-pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: true
  profiles:
    include: cache
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8083

custom:
  kafka:
    producers:
      bootstrap-servers: localhost:9092
      topic1:
        name: rental_result
    consumers:
      topic1:
        name: rental_rent
      topic2:
        name: rental_return
      group-id: book

