= API 문서
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

= 회원(Member)

== 회원 생성

=== request

operation::member-controller-test/create-member[snippets='http-request,request-fields']

=== response

operation::member-controller-test/create-member[snippets='http-response,response-fields']

= 공연(Performance)

== 공연 생성

=== request

operation::admin-performance-controller-test/create-performance[snippets='http-request,request-headers,request-fields']

=== response

operation::admin-performance-controller-test/create-performance[snippets='http-response']

== 공연 목록 조회

=== request

operation::user-performance-controller-test/get-performances[snippets='http-request']

=== response

operation::user-performance-controller-test/get-performances[snippets='http-response,response-fields']

== 공연 상세 조회

=== request

operation::user-performance-controller-test/get-performance[snippets='http-request']

=== response

operation::user-performance-controller-test/get-performance[snippets='http-response,response-fields']

= 좌석(Seat)

== 관리자 좌석 등급 생성 API

=== request

operation::admin-seat-controller-test/create-seat-grades[snippets='http-request,path-parameters,request-fields']

=== response

operation::admin-seat-controller-test/create-seat-grades[snippets='http-response']

== 관리자 좌석 생성 API

=== request

operation::admin-seat-controller-test/create-seats[snippets='http-request,path-parameters,request-fields']

=== response

operation::admin-seat-controller-test/create-seat-grades[snippets='http-response']

== 구역의 좌석 목록 조회

=== request

operation::seat-controller-test/get-seats[snippets='http-request,path-parameters']

=== response

operation::seat-controller-test/get-seats[snippets='http-response,response-fields']

== 공연의 좌석 등급 목록 조회

=== request

operation::seat-controller-test/get-seat-grades[snippets='http-request,path-parameters']

=== response

operation::seat-controller-test/get-seat-grades[snippets='http-response,response-fields']
