### Send POST request with body as prameters
POST http://localhost:8082/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "username": "test",
    "password": "111"
}

### Send POST request with json body
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send POST request with json body
POST http://localhost:8082/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "test",
  "password": "1111"
}