### Send POST request with body as prameters
POST http://localhost:8082/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
    "username": "test2",
    "password": "1111"
}

### Send POST request with body as prameters
POST http://localhost:8082/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "manager",
  "password": "1111"
}

### Send POST request with body as prameters
GET http://localhost:8082/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest
