server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: HikariPool-tickets
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
        show_sql: true # 콘솔로그로 출력하려면
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: "http://localhost:8080"
  access-expiry-seconds: 1800
  refresh-expiry-seconds: 3600
  secret-key: thisisjusttestaccesssecretsodontworry
cors:
  allowed:
    origins: http://localhost:3000,http://localhost:8080


ticketing:
  reservation:
    release-delay-seconds: 10