spring:
  application:
    name: spring-batch-test-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4=utf8mb4&8useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:my-secret-pw}
    driver-class-name: com.mysql.cj.jdbc.Driver