spring:
  application:
    name: spring-batch-test-service
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/batch?useSSL=false&serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4=utf8mb4&8useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:my-secret-pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  lifecycle:
    timeout-per-shutdown-phase: 20s
scheduler:
  date: 20210102
server:
  shutdown: graceful
logging:
  level:
    org.springframework.jdbc: DEBUG # 실행 시 SQL 로그를 보기 위해 설정