spring:
  application:
    name: popbill-service
popbill:
  #?????
  linkId: ${POPBILL_LINKID}
  #???
  secretKey: ${POPBILL_SECRETKEY}
  #???? ??, true-???, false-??(Production), (???:false)
  isTest: true
  #???? IP ?? ??, true-??, false-???, (???:true)
  isIpRestrictOnOff: true
  #?? IP ??, true-??, false-???, (???:false)
  useStaticIp: false
  #????? ?? ????, true-??, false-???, (???:true)
  useLocalTimeYn: true
  dev:
    corpNum: ${POPBILL_TEST_CORPNUM}
    userId: ${POPBILL_TEST_USERID}