my:
  datasource:
    url: local.db.com
    username: username
    password: password
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev_username
    password: dev_password
    etc:
      max-connection: 1
      timeout: 30s
      options: LOCAL, CACHE
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: prod_username
    password: prod_password
    etc:
      max-connection: 1
      timeout: 30s
      options: LOCAL, CACHE
