apiVersion: v1
kind: Pod
metadata:
  name: web-empty
  labels:
    role: web-empty
spec:
  containers:
    - name: web-empty
      image: nginx:1.14
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
  volumes:
    - name: html
      emptyDir: {}
  restartPolicy: Always
